### ISSUE TITLE
This project cannot run in my PC

### ISSUE THREAD

**Issue by BeeDawaree** [palmloftz/myRepository#1]
my PC install
php version 5.5 
apache version 2.4
why?

**Comment by palmloftz** [comment]
I'm not sure. Maybe you must use php version 6.0 because It's work for me.

**Comment by ekkanutza** [comment]
>> Google

**Comment by BeeDawaree** [comment]
OK. Thanks my Boss 555

**Comment by ekkanutza** [comment]
oh! you from Thailand ??

**Comment by BeeDawaree** [comment]
No no I'm from JP ^^
こんにちは
わたしは Bee Dawaree です
どうぞ　よろしく。

**Comment by palmloftz** [comment]
Ok Bye

**Comment by sanotk** [comment]
not bye

**Comment by BeeDawaree** [comment]
Bye

**Comment by ekkanutza** [comment]
Hello, Bee Welcome to myRepository group

**Comment by palmloftz** [comment]
Stop ! it notificate from my email away. I'm bored.
